### ISSUE TITLE
don't use the mod logo as button texture

### ISSUE THREAD

**Issue by AnhNguyenlost13** [TheBearodactyl/gay-wave-trail#5]
it makes the button MASSIVE when using medium texture quality

instead, make dedicated texture for the button so it can scale accordingly

**Comment by TheBearodactyl** [comment]
> [<img alt="@TheBearodactyl" width="40" height="40" src="https://avatars.githubusercontent.com/u/114454115?s=80&amp;v=4">](/TheBearodactyl)
> 
> 
> #### Add a comment

dude, either way it'd be an image, it'll just scale the same way
