### ISSUE TITLE
When enabled wave trail disables regular trail.

### ISSUE THREAD

**Issue by StatusZer0** [TheBearodactyl/gay-wave-trail#6]
when enabled, if you enter a wave portal and exit it, your trail (like fire or stripe) completely disables until you leave and re-enter the level

**Comment by TheBearodactyl** [comment]
> when enabled, if you enter a wave portal and exit it, your trail (like fire or stripe) completely disables until you leave and re-enter the level

then disable the setting to disable regular trail
